### ISSUE TITLE
has_one_attached causes error

### ISSUE THREAD

**Issue by ericraio** [marinosoftware/active_storage_drag_and_drop#1]
When using has_one_attached, it causes this exception

    reject delegated to attachment, but attachment is nil

**Comment by jamesoreillyms** [comment]
Hi @ericraio please use the following format when raising new issues.

### 1. Steps to reproduce
### 2. Expected behaviour
### 3. Actual behaviour
### 4. System configuration
**Rails version:** x.x.x
**Ruby version:** x.x.x
