### ISSUE TITLE
Make it work with Webpacker

### ISSUE THREAD

**Issue by AlainPilon** [marinosoftware/active_storage_drag_and_drop#14]
Since Rails 6 uses Webpacker,  `//= require active_storage_drag_and_drop
` does not work anymore.

**Comment by dwood-somniainc** [comment]
Definitely. The JS doesn't fire off...and I tried to re-create the second application.js to activate the asset pipeline.

**Comment by addisonmartin** [comment]
I would also like this issue to be fixed if possible.

**Comment by dwood-somniainc** [comment]
Can we still access the JS using the Rails Asset Pipeline? Or no.........

**Comment by dwood-somniainc** [comment]
Read this stackoverflow post guys. Its a working solution for Rails 6

[](https://stackoverflow.com/questions/59346100/import-gems-javascript-folder-with-rails-webpacker-rails-erb-loader)
